package services

import (
	"crypto/tls"
	"errors"
	"fmt"
	"net/smtp"
	"strings"

	"gopanel/internal/config"
)

// SendEmail dispatches an email using the active SMTP configuration
func SendEmail(to string, subject string, bodyHTML string) error {
	cfg := config.GetEmailSettings()
	if cfg.Host == "" {
		return errors.New("email configuration is not set up")
	}

	from := cfg.From
	if from == "" {
		from = cfg.Username
	}

	// Build the email message
	header := make(map[string]string)
	header["From"] = from
	header["To"] = to
	header["Subject"] = subject
	header["MIME-Version"] = "1.0"
	header["Content-Type"] = "text/html; charset=\"utf-8\""

	message := ""
	for k, v := range header {
		message += fmt.Sprintf("%s: %s\r\n", k, v)
	}
	message += "\r\n" + bodyHTML

	addr := cfg.Host + ":" + cfg.Port

	var auth smtp.Auth
	// Many providers skip password if none is provided via IP-whitelist etc, but normally we authenticate.
	if cfg.Username != "" {
		auth = smtp.PlainAuth("", cfg.Username, cfg.Password, cfg.Host)
	}

	// Handle direct TLS (port 465) vs STARTTLS (port 587/2525)
	if cfg.Secure || cfg.Port == "465" {
		return sendMailDirectTLS(addr, auth, from, []string{to}, []byte(message), cfg)
	}

	// Default to standard smtp.SendMail (uses STARTTLS automatically if the server supports it)
	return smtp.SendMail(addr, auth, from, []string{to}, []byte(message))
}

// sendMailDirectTLS handles SMTP over implicit TLS (SMTPS) which standard smtp.SendMail doesn't do natively
func sendMailDirectTLS(addr string, auth smtp.Auth, from string, to []string, msg []byte, cfg config.EmailSettings) error {
	tlsConfig := &tls.Config{
		ServerName: cfg.Host,
	}

	conn, err := tls.Dial("tcp", addr, tlsConfig)
	if err != nil {
		return fmt.Errorf("tls dial error: %w", err)
	}
	defer conn.Close()

	client, err := smtp.NewClient(conn, cfg.Host)
	if err != nil {
		return fmt.Errorf("smtp new client error: %w", err)
	}
	defer client.Close()

	if auth != nil {
		if ok, _ := client.Extension("AUTH"); ok {
			if err = client.Auth(auth); err != nil {
				return fmt.Errorf("auth error: %w", err)
			}
		}
	}

	if err = client.Mail(from); err != nil {
		return fmt.Errorf("mail from error: %w", err)
	}
	for _, addr := range to {
		if err = client.Rcpt(addr); err != nil {
			return fmt.Errorf("rcpt error: %w", err)
		}
	}

	w, err := client.Data()
	if err != nil {
		return fmt.Errorf("data cmd error: %w", err)
	}
	_, err = w.Write(msg)
	if err != nil {
		return fmt.Errorf("data write error: %w", err)
	}
	err = w.Close()
	if err != nil {
		return fmt.Errorf("data close error: %w", err)
	}
	return client.Quit()
}

// SendTestEmail sends a simple verification email
func SendTestEmail(to string) error {
	subject := "GoPanel - Email Configuration Test"
	body := `
	<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
		<h2 style="color: #3b82f6;">Configuration Successful! 🎉</h2>
		<p>If you are reading this email, it means your GoPanel SMTP integration is successfully configured and working through your chosen provider.</p>
		<p style="color: #64748b; font-size: 13px; margin-top: 30px;">This is an automated message generated by your GoPanel Ecosystem.</p>
	</div>
	`

	// Validate 'to' contains something that looks like an email
	if !strings.Contains(to, "@") {
		return errors.New("invalid destination email address")
	}

	return SendEmail(to, subject, body)
}
